"use strict";

window.addEventListener("load", () => {
  const args = window.arguments?.[0] || {};
  const preview = args.preview || {};
  const submission = args.submission || {};
  const field = (id) => document.getElementById(id);
  const send = field("send");
  const retry = field("retry");
  const resend = field("resend");
  const status = field("status");
  const warning = field("warning");

  field("from").value = preview.credentials?.from || submission.from || "Set secure credentials in FeedRank settings";
  field("to").value = preview.credentials?.to || submission.to || "Set secure credentials in FeedRank settings";
  field("subject").value = preview.subject || "FeedRank — Research digest";
  field("server").value = preview.credentials?.host
    ? preview.credentials.host + ":" + (preview.credentials.port || "") +
      " (" + (preview.credentials.tlsMode || "unknown TLS mode") + ")"
    : "Set the SMTP server in FeedRank settings";
  field("plain-text").value = preview.text || "No prepared digest is available.";

  // The message is generated by FeedRank's escaping helper. Keep it in a
  // fully sandboxed srcdoc document nevertheless: no script, form, same-origin
  // access, popup, or network privilege is granted to the preview content.
  const frame = field("html-preview");
  const csp = "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; img-src 'none'; media-src 'none'; connect-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'\">";
  frame.setAttribute("srcdoc", "<!doctype html><html><head>" + csp + "</head>" + String(preview.html || "<body><p>No prepared digest is available.</p></body>") + "</html>");

  if (preview.preparationError) {
    warning.textContent = preview.preparationError + " The body can be reviewed, but Send remains disabled.";
  } else if (submission.status === "accepted") {
    warning.textContent = "The SMTP server already accepted this exact message. FeedRank will not send it again. SMTP cannot confirm inbox delivery.";
  } else if (submission.status === "unknown") {
    warning.textContent = "Delivery is unknown. Check the recipient mailbox before acting; FeedRank will not resend this message automatically.";
  } else if (submission.status === "retryable") {
    warning.textContent = "This message was not submitted. A manual retry reuses the exact frozen message byte for byte.";
  }
  if (submission.messageSubmitted && submission.status !== "accepted") {
    warning.textContent += " The message body had already been submitted to the server, so a duplicate is possible.";
  }

  send.disabled = !(preview.frozen && submission.status === "prepared" && typeof args.send === "function");
  retry.disabled = !(args.retryKey && submission.status === "retryable" && typeof args.retry === "function");
  resend.disabled = !(args.resendKey && submission.status === "unknown" && typeof args.resend === "function");

  const invoke = async (action, button) => {
    send.disabled = true;
    retry.disabled = true;
    resend.disabled = true;
    status.textContent = "Submitting one manual message…";
    try {
      const result = await action();
      status.textContent = result?.message || "No message was sent.";
      if (result?.status === "retryable" && typeof args.retry === "function") {
        retry.disabled = false;
      }
    } catch (error) {
      status.textContent = String(error?.message || error || "Email action failed.");
      if (button === send && preview.frozen && submission.status === "prepared") send.disabled = false;
      if (button === retry && args.retryKey) retry.disabled = false;
      if (button === resend && typeof args.resend === "function") resend.disabled = false;
    }
  };

  send.addEventListener("click", () => invoke(() => args.send(), send));
  retry.addEventListener("click", () => invoke(() => args.retry(args.retryKey), retry));
  resend.addEventListener("click", () => invoke(() => args.resend(args.resendKey), resend));
  field("close").addEventListener("click", () => window.close());
});
